name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: CICD
      type: github
      ref: main
      name: nhatthaiquang-agilityio/Terraform-CI-CD
      endpoint: nhatthaiquang-agilityio

variables:
  - name: TerraformWorkingDirectory
    value: $(System.DefaultWorkingDirectory)/Terraform
  - name: AzureServiceConnection
    value: 'AzureServiceConnection'

stages:
  - stage: ServiceBusInfrastructure
    displayName: Test - Setup Infrastructure
    jobs:
      - template: jobs/setup-azure-infrastructure.yml@CICD
        parameters:
          EnvironmentName: Test
          TerraformWorkingDirectory: '${{ variables.TerraformWorkingDirectory }}'
          AzureServiceConnectionName: '${{ variables.AzureServiceConnection }}'
          AzureResourceGroupName: 'RG-ExampleAzureFunctions'
          StorageAccountsName: 'tfinfrastructurestorage'
          AzureContainerName: 'tfinfrastructurecontainer'
          AzureRmKeyTFState: 'test.service-bus-infrastructure.tfstate'
